In [13]:
import torch
import numpy as np

np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print(
    '\nnumpy array:', np_data,          # [[0 1 2], [3 4 5]]
    '\ntorch tensor:', torch_data,      #  0  1  2 \n 3  4  5    [torch.LongTensor of size 2x3]
    '\ntensor to array:', tensor2array, # [[0 1 2], [3 4 5]]
)


numpy array: [[0 1 2]
 [3 4 5]] 
torch tensor: tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) 
tensor to array: [[0 1 2]
 [3 4 5]]


In [17]:
type(tensor2array)

numpy.ndarray

In [23]:
data = [[1,2],[3,4]]

In [24]:
tensor = torch.FloatTensor(data)

In [25]:
np.matmul(data,data)

array([[ 7, 10],
       [15, 22]])

In [42]:
import torch
from torch.autograd import Variable

In [43]:
tensor= torch.FloatTensor([[1,2],[3,4]])

In [44]:
variable = Variable(tensor,requires_grad=True)
type(variable)

torch.Tensor

In [35]:
print(tensor)

tensor([[1., 2.],
        [3., 4.]])


In [36]:
print(variable)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [37]:
t_out = torch.mean(tensor*tensor)       # x^2
v_out = torch.mean(variable*variable)   # x^2
print(t_out)
print(v_out) 

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward1>)


In [38]:
print(variable)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [39]:
print(variable.data)

tensor([[1., 2.],
        [3., 4.]])


In [40]:
print(variable.data.numpy())

[[1. 2.]
 [3. 4.]]


In [45]:
import torch
import torch.nn.functional as F
from torch.autograd import Variable

In [ ]:
x = torch.linspace(-5,5,200)
x = Variable(x)